# Vagrantfile

Vagrant.configure("2") do |config|
  # Configuração da imagem base para ambas as VMs
  config.vm.box = "bento/ubuntu-20.04"

  # Definição-VM1
  config.vm.define "node1" do |node1| # <-- O objeto da VM é 'node1'
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.56.11"

    # Provisionamento-VM1
    node1.vm.provision "shell", inline: <<-SHELL
      apt-get update
    
    SHELL
  end

  # Definição-VM2
  config.vm.define "node2" do |node2| # <-- O objeto da VM é 'node2'
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.56.12"

    # Provisionamento-VM2
    node2.vm.provision "shell", inline: <<-SHELL
      apt-get update
    SHELL
  end
end

## Teste com sucesso.
